[build]
  publish = "."
  functions = "netlify/functions" # Optional, for backend functions

[dev]
  publish = "." # Serve files from the root directory
  port = 1337   # Set custom port to 1337
  autoLaunch = false # Prevent automatic browser opening